version: '3.8'

services:
  newsapi:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/news"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s 